version: "2"
plugins:
  rubocop:
    enabled: true
  eslint:
    enabled: false
  csslint:
    enabled: true
  duplication:
    enabled: false
    languages:
      - ruby

exclude_patterns:
- spec/**/*
